=== kusku/mvuab-11-12-g1/trunk/EngineUAB/Run/Test_Hito_Mayo/Data/XML/characters_animated_states.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="characters">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="default_states">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="state">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="animation">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="core" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" maxOccurs="1" name="player">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="1" maxOccurs="unbounded" name="state">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="animation">
                      <xs:complexType>
                        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="core" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
        <xs:element name="enemies">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="enemy">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="state">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="1" maxOccurs="unbounded" name="animation">
                            <xs:complexType>
                              <xs:attribute name="id" type="xs:unsignedByte" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="core" type="xs:string" use="required" />
                  <xs:attribute name="animated_instace_name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kusku/mvuab-11-12-g1/EngineUAB/Run/Videogame/Data/XML/characters_animated_states.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='characters_animated_states.xsd'>
  <default_states core="caperucita">
    <state name="idle">
      <animation id="0"  />
    </state>
    <state name="run">
      <animation id="1"  />
    </state>
    <state name="attack">
      <animation id="2"  />
    </state>
  </default_states>
  <default_states core="lobo">
    <state name="idle">
      <animation id="0"  />
    </state>
    <state name="walk">
      <animation id="1"  />
    </state>
    <state name="run">
      <animation id="2"  />
    </state>
  </default_states>
  <player name="Jolete" core="caperucita">
  </player>
  <enemies>
    <enemy name="enemy1" core="lobo" animated_instace_name="lobo1" />
  </enemies>
</characters>

=== kusku/mvuab-11-12-g1/EngineUAB/Run/Test_Behaviour/Data/XML/characters_animated_states - copia.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<characters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation='characters_animated_states.xsd'>
  <default_states core="caperucita">
    <state name="idle">
      <animation id="0"  />
      <animation id="1"  />
      <animation id="2"  />
      <animation id="4"  />
    </state>	
    <state name="run">
      <animation id="2"  />
      <animation id="3"  />
    </state>
    <state name="pursuit">
      <animation id="2"  />
      <animation id="3"  />
      <animation id="5"  />
    </state>
  </default_states>
  <default_states core="lobo">
    <state name="idle">
      <animation id="0"  />
      <animation id="1"  />
    </state>
    <state name="run">
      <animation id="0"  />
      <animation id="1"  />
      <animation id="2"  />
      <animation id="4"  />
    </state>
  </default_states>
  <player name="Jolete" core="caperucita">
    <state name="idle">
      <animation id="0"  />
	  <animation id="10"  />
    </state>
    <state name="run">
      <animation id="3"  />
	  <animation id="2"  />
	  <animation id="1"  />
    </state>
  </player>
  <enemies>
    <enemy name="enemy1" core="lobo" animated_instace_name="lobo1" >
      <state name="idle">
        <animation id="3"  />
        <animation id="15"  />
      </state>
      <state name="run">
        <animation id="32"  />
        <animation id="33"  />
      </state>
    </enemy>
    <enemy name="enemy2" core="lobo" animated_instace_name="lobo2" >
      <state name="idle">
        <animation id="8"  />
        <animation id="7"  />
      </state>
      <state name="run">
        <animation id="6"  />
        <animation id="9"  />
      </state>
    </enemy>
  </enemies>
</characters>
